#ifndef AutoStabilizer_idl
#define AutoStabilizer_idl

#include "ExtendedDataTypes.idl"

module auto_stabilizer_msgs
{
  struct LandingPositionIdl
  {
    double x;
    double y;
    double z;
    double nx;
    double ny;
    double nz;
    long l_r; // 0: right. 1: left.
  };

  struct SteppableRegionIdl
  {
    sequence<sequence<double> > region;
    long l_r; // 0: right. 1: left.
  };

  struct TimedLandingPosition
  {
    RTC::Time tm;
    LandingPositionIdl data;
  };
  struct TimedSteppableRegion
  {
    RTC::Time tm;
    SteppableRegionIdl data;
  };

  struct FootStepNodes
  {
    sequence<RTC::Pose3D> dstCoords; // generate frame 0:right. 1: left.
    sequence<boolean> isSupportPhase;
    double remainTime;
  };

  struct TimedFootStepNodesList
  {
    RTC::Time tm;
    sequence<FootStepNodes> data;
  };

  struct ComPredictParam
  {
    RTC::Point3D curZmp;
    RTC::Point3D curCog;
    RTC::Point3D curCogVel;
    double omega;
    RTC::Point3D l;
    double dt;
  };
};

#endif
